# Generated by Django 4.2.7 on 2023-11-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
